[Interface]
# Ваш приватный ключ
PrivateKey = pKqWVC4zIQ0XV3hysgtsVuddIekHgHEvv2oPGAfdU00=
# IP адрес в VPN сети
Address = 192.168.1.205/24
# DNS серверы (опционально)
DNS = 192.168.1.10, 1.1.1.1, 8.8.8.8

[Peer]
# Публичный ключ сервера
PublicKey = 3LRk0exiOVDuvYtLZXi0GHliE36qkh1qMBfeaLopWmU=
# Endpoint сервера (IP:порт)
Endpoint = 31.129.207.13:3389
# Разрешенные IP (0.0.0.0/0 = весь трафик через VPN)
AllowedIPs = 0.0.0.0/0
# Keepalive для поддержания соединения
PersistentKeepalive = 10
